### PR TITLE
Code explanations

### PR DESCRIPTION
**Pull request by kamil-kaczmarek**

### CODE REVIEW

**Comment by emmyscode** [comment]
Give me five minutes, I'll push everything else I have :)

**Comment by kamil-kaczmarek** [comment]
@emmyscode of course :)

**Review by emmyscode — APPROVED** [review]
Okay, the rest of the copy changes can wait until after the merge as they depend on the code changes anyways.

**Comment by kamil-kaczmarek** [comment]
ok

**Pull request merged**
