### PR TITLE
Introduction to Ray AIR Revision

### PR DESCRIPTION
**Pull request by emmyscode**
# Changes summary

*Summary of changes in this PR*

Revision to Introduction to Ray AIR module based on feedback collected after Ray Saturday.

Notable changes include:
* standardizing code snippets
* add additional context to code snippets
* adding more links and resources into each section
* adding in comments about support for heterogeneous hardware
* adding in explanation of a checkpointing strategy
* fix list styling
* general revisions for clarity

# PR scope

* [ ] new notebook
* [x] improvements to the existing notebook
* [ ] bug fixes
* [ ] other

# Checklist

* [x] notebook is without outputs
* [x] empty cells are removed
* [x] code is formatted with [black](https://github.com/psf/black)
* [x] imports are sorted
* [ ] if new notebook is added, README is updated

### CODE REVIEW

**Comment by kamil-kaczmarek** [comment]
@emmyscode let modify code images according to the style guide.

**Review by kamil-kaczmarek — CHANGES_REQUESTED** [review]
- code images -> fix to be coherent with the style guide (line numbers and ray logo)
- add style hints as in Overview of Ray
- apply lists style as you introduced in Overview of Ray.

**Comment by emmyscode** [comment]
This is as polished as this module can get 😅

**Comment by emmyscode** [comment]
This is as polished as this module can get 😅

**Review by kamil-kaczmarek — APPROVED** [review]
lgtm!

**Pull request merged**
